services:
  db:
    container_name: db
    image: postgres:15-alpine
    networks:
      - network
    env_file:
      - ./.env.dev
    volumes:
      - db:/var/lib/postgresql/data

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: apps/docker/backend/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
    networks:
      - network
    volumes:
      - static:/apps/ciroautuori/static
      - media:/apps/ciroautuori/media

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: apps/docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./.env.dev
    networks:
      - network

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: apps/docker/nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./.env.dev
    volumes:
      - static:/apps/ciroautuori/static
      - media:/apps/ciroautuori/media
      - /etc/letsencrypt:/etc/letsencrypt
      - ./apps/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - network
    depends_on:
      - backend
      - frontend

networks:
  network:
    driver: bridge

volumes:
  db:
    name: db
  node_modules:
  static:
    name: static
  media:
    name: media
