# Generated by Django 4.2.18 on 2025-01-21 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("abouts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="education",
            old_name="img",
            new_name="icon",
        ),
    ]
