# Generated by Django 4.2.18 on 2025-01-21 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("abouts", "0002_rename_img_education_icon"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WorkExp",
            new_name="Experinence",
        ),
    ]
