# Generated by Django 5.1.5 on 2025-01-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abouts", "0003_rename_workexp_experinence"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("icon", models.ImageField(upload_to="skills/")),
            ],
            options={
                "verbose_name_plural": "Skills",
            },
        ),
        migrations.RemoveField(
            model_name="about",
            name="education",
        ),
        migrations.RemoveField(
            model_name="about",
            name="location",
        ),
        migrations.RemoveField(
            model_name="about",
            name="title",
        ),
        migrations.RemoveField(
            model_name="about",
            name="work_experience",
        ),
        migrations.AddField(
            model_name="about",
            name="github",
            field=models.URLField(default="https://github.com/"),
        ),
        migrations.AddField(
            model_name="about",
            name="linkedin",
            field=models.URLField(default="https://linkedin.com/"),
        ),
    ]
