# Generated by Django 5.1.5 on 2025-01-29 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("abouts", "0004_skill_remove_about_education_remove_about_location_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="experinence",
            old_name="roles",
            new_name="description",
        ),
    ]
